[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
description = 'Implementation of "Automated characterization of noise distributions in diffusion MRI data".'
name = "autodmri"
version = '0.2.8'
authors = [{ name = "Samuel St-Jean" }]
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"

dependencies = [
    'numpy>=1.20',
    'scipy>=1.0',
    'tqdm>=4.56',
    'joblib>=1.0',
    'nibabel>=3.2',
]

[project.scripts]
autodmri_get_distribution = "autodmri.scripts:main"

[project.urls]
homepage = "https://github.com/samuelstjean/autodmri"
documentation = "https://samuelstjean.github.io/autodmri/"
changelog = "https://github.com/samuelstjean/autodmri/blob/master/CHANGELOG.md"

[tool.setuptools]
packages = ["autodmri"]
